# Generated by Django 4.1.7 on 2023-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=3, max_digits=4)),
                ('lugar_recogida', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
