# Generated by Django 4.1.7 on 2023-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarDestinos', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='monto',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
