# Generated by Django 4.1.7 on 2023-05-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarDestinos', '0003_alter_destino_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
