# Generated by Django 4.1.7 on 2023-06-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categorias',
        ),
    ]
