# Generated by Django 4.2.1 on 2023-06-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_blog_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='info',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.TextField(max_length=10000),
        ),
    ]
