# Generated by Django 4.2.1 on 2023-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_info_alter_blog_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.ManyToManyField(to='Blog.categoria'),
        ),
    ]
